# This command tells Netlify how to build the frontend.
# It navigates into the 'client' folder and runs 'npm run build'.
[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"
  functions = "netlify/functions/" # Specifies the directory for serverless functions.

# This rule proxies all API requests to our serverless function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# This is a "catch-all" rule for the React app. It ensures that
# client-side routing works correctly by serving the main HTML file for any non-API path.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
