# =============================================================================
#  Netlify Configuration File
#  This file contains settings for building and deploying your site on Netlify.
# =============================================================================

# [build] section: Contains the main build settings for your site.
[build]
  # Command to run to build your site.
  # Examples: "npm run build", "hugo", "jekyll build"
  command = "npm run build"

  # Directory that contains your serverless functions.
  # Netlify will automatically deploy functions from this directory.
  functions = "netlify/functions"

  # Directory to deploy. This is the directory that contains the final static
  # assets of your site after the build command has completed.
  # Examples: "dist", "build", "public"
  publish = "dist"

# [dev] section: Contains settings for running netlify dev (local development).
[dev]
  # The command to run your local development server.
  command = "npm start"

  # The port for your local development server.
  port = 3000

  # The port for the Netlify Dev server to listen on.
  # This is useful if your framework has a specific port requirement.
  targetPort = 8888

# [[redirects]] section: Define HTTP redirects.
# You can have multiple redirect rules.
[[redirects]]
  # The original path.
  from = "/old-path"

  # The new path to redirect to.
  to = "/new-path"

  # The HTTP status code for the redirect.
  # 301 = Permanent Redirect, 302 = Temporary Redirect.
  status = 301

  # Set to true to make the redirect apply only when the "from" path
  # does not have a corresponding file.
  # force = false

# [[headers]] section: Define custom HTTP headers for specific paths.
[[headers]]
  # The path for which these headers should be applied.
  # "/*" applies to all pages.
  for = "/*"
    [headers.values]
    # Example: Basic security headers.
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"